server:
  port: 8080

spring:
  thymeleaf:
   cache: false
   mode: HTML
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: school-provider
            client-id : client-school
            client-secret : secret
            client-authentication-method : basic
            authorization-grant-type: authorization_code
            scope : profile
            client-name : Login Client
            redirect-uri-template : "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          school-provider:
            authorization-uri: http://localhost:8764/oauth/authorize
            token-uri: http://localhost:8764/oauth/token
            user-info-uri : http://localhost:8764/resources/userinfo
            user-name-attribute : name   

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    

